### ISSUE TITLE
finalize admin only pages-- create separate admin component folder for all users, modify products

### ISSUE THREAD

**Issue by se7en-illa** [GOOD-TIMES-CREW/graceshopper-10-2022#75]
FRONT END

- [x] only admin should be able to modify products
   - [x]  add
   - [x] remove
- [x] only admin can see all users 
- [x] only admin can see all orders

BACK END
- [x] Only admins should have access to the api route for all users 
- [x] Only admins should have access to the api POST routes for products
- [x] -Only admins should have access to the api DELETE routes for products
- [x] Users cannot make themselves an admin through the user signup route

**Comment by JNOGUE** [comment]
Didn't make an admin folder because all files already existed in user folder.
